### ISSUE TITLE
[Bug] Comet Lake Desktop (Booter/Quirks/ProtectUefiServices)

### ISSUE THREAD

**Issue by 5T33Z0** [ocwebutils/rules#3]
When testing the config of my 10th Gen Intel Core Desktop, I noticed there's an error in one of the Booter Quirks matches.

## Booter/Quirks
- (Quirks) ProtectUefiServices: **Enabled**; Error Message: "ProtectUefiServices **must be disabled**"

&rarr; This is wrong. According to the OC Install Guide, `ProtectUEFIServices`must be **enabled**. Reference: https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#booter

Greetings.

**Comment by sunbos** [comment]
<img width="2032" alt="picture1" src="https://user-images.githubusercontent.com/21107549/212367832-abcbf93a-88e5-45ac-bb5a-ec82cf82a57b.png">
<img width="2032" alt="picture2" src="https://user-images.githubusercontent.com/21107549/212367971-7c67d07c-2c48-452a-9a51-5ce8616485ec.png">

**Comment by ririxidev** [comment]
I will not change the desired value, however I will change a text that is showing. Only Icelake and Z390 requires it on laptops. On desktop it's required by Z490 only so that will be changed as well

**Comment by rxri** [comment]
After looking at dortania guide - expected value will not change, however the shown message will be changed to reflect that it’s only required for Z390 socket

**Comment by 5T33Z0** [comment]
Uhh… you are wrong again. It is required for Z490, not Z390. Quote from "More In-depth Info":

> Protects UEFI services from being overridden by the firmware, required for Z490.

**Comment by ririxidev** [comment]
> Uhh… you are wrong again. It is required for Z490, not Z390. Quote from "More In-depth Info":
> 
> > Protects UEFI services from being overridden by the firmware, required for Z490.

I'm not wrong. @sunbos provided screenshots about laptop one, so that's what I'm talking about
> ![image](https://user-images.githubusercontent.com/9348108/212409815-715b5caa-086d-4154-ba5a-367d2944a2bf.png)

This quirk is required on Desktop on Z490 socket
![image](https://user-images.githubusercontent.com/9348108/212409972-643f0e66-e99d-40e2-b01a-379f1511a86e.png)

**Comment by rxri** [comment]
> Uhh… you are wrong again. It is required for Z490, not Z390. Quote from "More In-depth Info":
> 
> > Protects UEFI services from being overridden by the firmware, required for Z490.

@sunbos is specifically mentioning **laptop** rules in their screenshots. I'm not sure why they posted these screenshots there since this is an issue about Desktop rules
> ![image](https://user-images.githubusercontent.com/9348108/212409815-715b5caa-086d-4154-ba5a-367d2944a2bf.png)

However, like you mentioned, this quirk is required on **Desktop** with Z490 socket

**Comment by 5T33Z0** [comment]
Ah, ok. I mean the Topic is about Desktops. 

But there's another issue with the Laptop Installation Guide which is a concern for evaluating the suggested setting:  Z390 and Z490 are Desktop chipsets exclusively. Mobile chipsets for 9th and 10th gen Intel  have completely differnent names:

9th Gen: https://en.wikipedia.org/wiki/List_of_Intel_chipsets#Mobile_chipsets_2
10 Gen: https://en.wikipedia.org/wiki/List_of_Intel_chipsets#Mobile_and_embedded_chipsets

Therefore, referring to Z390 in the Installation guide makes absolutely no sense in regards to Laptops. 

This is not your fault of course, since you didn't write the guide. But I wouldn't quote Z390 in the context of a Laptop config.

**Comment by rxri** [comment]
If that's a case, then I will change the expected value to `Enabled` in Laptop rules

**Comment by 5T33Z0** [comment]
I think that's a good idea.
